import React, { useState, useEffect, useCallback } from 'react';
import Modal from '../ui/Modal';
import { User } from '../../types';
import { generateUuid, calculateLoyaltyTier } from '../../utils/helpers';

interface RegisterModalProps {
    isOpen: boolean;
    onClose: () => void;
    onRegister: (newUser: User) => void;
    registeredUsers: User[];

    onOpenLogin: () => void;
    role?: string;
    initialReferralCode?: string;
}

const RegisterModal: React.FC<RegisterModalProps> = ({ isOpen, onClose, onRegister, registeredUsers = [], onOpenLogin, initialReferralCode }) => {
    const [name, setName] = useState<string>('');
    const [phone, setPhone] = useState<string>('');
    const [password, setPassword] = useState<string>('');
    const [referrerCode, setReferrerCode] = useState<string>(initialReferralCode || '');

    // Errors
    const [phoneError, setPhoneError] = useState<string>('');
    const [passwordError, setPasswordError] = useState<string>('');
    const [referrerError, setReferrerError] = useState<string>('');

    // NEW: Referral code validation handler
    const handleReferralCodeChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        const value = e.target.value.trim();
        setReferrerCode(value);

        if (value.length === 0) {
            setReferrerError(''); // Clear error if empty
        } else {
            // FIXED: Case-insensitive search with trim
            const codeExists = registeredUsers.some(u =>
                u.referralCode.toLowerCase() === value.toLowerCase()
            );
            if (codeExists) {
                setReferrerError('✓ Código válido'); // Success message
            } else {
                setReferrerError('✗ Código no encontrado');
            }
        }
    }, [registeredUsers]);

    const handlePhoneChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        const value = e.target.value.replace(/\D/g, '');
        setPhone(value);
        if (value.length > 11) {
            // Block input longer than 11
        } else if (value.length !== 11 && value.length > 0) {
            setPhoneError('El número debe tener 11 dígitos.');
        } else if (registeredUsers.some(u => u.phone === value)) {
            setPhoneError('Este número ya está registrado.');
        } else {
            setPhoneError('');
        }
    }, [registeredUsers]);

    const handlePasswordChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        const value = e.target.value;
        setPassword(value);
        if (value.length > 0 && value.length < 4) { // Simplified password requirement as per user request
            setPasswordError('Mínimo 4 caracteres.');
        } else {
            setPasswordError('');
        }
    }, []);

    // Allow form submission if referrer error is success message or empty
    const isFormValid = phone.length === 11 && password.length >= 4 && !phoneError && !passwordError && (referrerError === '' || referrerError.startsWith('✓'));

    const handleSubmit = useCallback((e: React.FormEvent) => {
        e.preventDefault();

        if (!isFormValid) {
            if (phone.length !== 11) setPhoneError('Requerido 11 dígitos.');
            if (password.length < 4) setPasswordError('Mínimo 4 caracteres.');
            return;
        }

        // Final duplicate check
        if (registeredUsers.some(u => u.phone === phone)) {
            setPhoneError('Este número ya está registrado. Inicia Sesión.');
            return;
        }

        const newReferralCode = generateUuid();
        const autoGeneratedEmail = `${phone}@rayburger.app`;

        const newUser: User = {
            email: autoGeneratedEmail,
            name: name.trim() || 'Amante de Burger', // Default name
            phone: phone,
            passwordHash: password,
            referralCode: newReferralCode,
            referredByCode: referrerCode || undefined,
            points: 0,
            loyaltyTier: calculateLoyaltyTier(0),
            orders: [],
            role: 'customer'
        };

        onRegister(newUser);
        // Reset Form
        setName('');
        setPhone('');
        setPassword('');
        setReferrerCode('');

    }, [isFormValid, name, phone, password, referrerCode, onRegister, registeredUsers]);

    useEffect(() => {
        if (!isOpen) {
            // Reset fields on close, keep referral code if it was passed initially? 
            // Better to reset fully except if prop persists.
            setName('');
            setPhone('');
            setPassword('');
            setReferrerCode(initialReferralCode || '');
            setPhoneError('');
            setPasswordError('');
            // Don't reset referrer error yet, wait for validation
            setReferrerError('');
        } else {
            // If opening, ensure code from prop is set
            if (initialReferralCode) {
                setReferrerCode(initialReferralCode);
                // Trigger validation logic for initial code?
                // Simple check:
                const codeExists = registeredUsers?.some(u => u.referralCode?.toLowerCase() === initialReferralCode.toLowerCase());
                if (codeExists) setReferrerError('✓ Código válido (desde enlace)');
            }
        }
    }, [isOpen, initialReferralCode, registeredUsers]);

    const handleLoginRedirect = useCallback(() => {
        onClose();
        onOpenLogin();
    }, [onClose, onOpenLogin]);


    return (
        <Modal isOpen={isOpen} onClose={onClose} title="Únete al Club RayBurger">
            <form onSubmit={handleSubmit} className="space-y-4">

                {/* Phone Field (Mandatory) */}
                <div>
                    <label htmlFor="registerPhone" className="block text-white text-lg font-semibold mb-2">
                        Número de Teléfono (11 dígitos) <span className="text-red-500">*</span>
                    </label>
                    <input
                        id="registerPhone"
                        type="tel"
                        pattern="[0-9]{11}"
                        maxLength={11}
                        placeholder="Ej: 04121234567"
                        value={phone}
                        onChange={handlePhoneChange}
                        required
                        className={`w-full px-4 py-3 rounded-md bg-gray-700 text-white border-2 ${phoneError ? 'border-red-500' : 'border-gray-600'} focus:border-orange-500 focus:ring-1 focus:ring-orange-500 transition-all duration-300 placeholder-gray-400 text-lg`}
                    />
                    {phoneError && (
                        <p className="text-red-500 text-sm mt-1 flex items-center">
                            {phoneError}
                            {phoneError.includes('ya está registrado') && (
                                <button type="button" onClick={handleLoginRedirect} className="ml-2 text-orange-400 hover:underline">
                                    Entrar
                                </button>
                            )}
                        </p>
                    )}
                </div>

                {/* Password Field */}
                <div>
                    <label htmlFor="registerPassword" className="block text-white text-lg font-semibold mb-2">
                        Clave secreta <span className="text-red-500">*</span>
                    </label>
                    <input
                        id="registerPassword"
                        type="password"
                        placeholder="Algo que recuerdes"
                        value={password}
                        onChange={handlePasswordChange}
                        required
                        minLength={4}
                        className={`w-full px-4 py-3 rounded-md bg-gray-700 text-white border-2 ${passwordError ? 'border-red-500' : 'border-gray-600'} focus:border-orange-500 focus:ring-1 focus:ring-orange-500 transition-all duration-300 placeholder-gray-400 text-lg`}
                    />
                    {passwordError && <p className="text-red-500 text-sm mt-1">{passwordError}</p>}
                </div>

                {/* Nombre (Opcional) */}
                <div>
                    <label htmlFor="registerName" className="block text-white text-sm mb-1">Tu Nombre (opcional)</label>
                    <input
                        id="registerName"
                        type="text"
                        placeholder="¿Cómo te decimos?"
                        value={name}
                        onChange={(e) => setName(e.target.value)}
                        className="w-full px-4 py-2 rounded-md bg-gray-700 text-white border border-gray-600 focus:border-orange-500 outline-none transition-colors"
                    />
                </div>

                {/* Referrer */}
                <div className="mt-2">
                    <label htmlFor="referrerCode" className="block text-white text-sm mb-1">¿Tienes código de referido?</label>
                    <input
                        id="referrerCode"
                        type="text"
                        placeholder="Pégalo aquí"
                        value={referrerCode}
                        onChange={handleReferralCodeChange}
                        className={`w-full px-4 py-2 rounded-md bg-gray-700 text-white border ${referrerError.startsWith('✓') ? 'border-green-500' : referrerError.startsWith('✗') ? 'border-red-500' : 'border-gray-600'} focus:border-orange-500 outline-none transition-colors`}
                    />
                    {referrerError && (
                        <p className={`text-sm mt-1 ${referrerError.startsWith('✓') ? 'text-green-400' : 'text-red-400'}`}>
                            {referrerError}
                        </p>
                    )}
                </div>

                <button
                    type="submit"
                    disabled={!isFormValid}
                    className={`w-full mt-6 py-3 rounded-full text-lg font-bold transition-transform transform active:scale-95 duration-200 ${isFormValid ? 'bg-orange-600 hover:bg-orange-700 text-white shadow-lg shadow-orange-900/40' : 'bg-gray-600 text-gray-400 cursor-not-allowed'
                        }`}
                >
                    ¡Registrarme!
                </button>
            </form>
            <p className="text-gray-400 text-center mt-4 text-sm">
                ¿Ya eres parte del club?{' '}
                <button type="button" onClick={handleLoginRedirect} className="text-orange-400 hover:underline font-bold">
                    Entra aquí
                </button>
            </p>
        </Modal>
    );
};

export default RegisterModal;
