import React, { useState, useEffect, useCallback } from 'react';
import { Loader2 } from 'lucide-react';
import Modal from '../ui/Modal';
import { User } from '../../types';
import { normalizePhone } from '../../utils/helpers';
import { mapDbUserToApp } from '../../utils/dbMapper';
import { getDeviceFingerprint } from '../../utils/helpers';

interface RegisterModalProps {
    isOpen: boolean;
    onClose: () => void;
    onRegister: (newUser: User) => void;
    registeredUsers: User[];

    onOpenLogin: () => void;
    role?: string;
    initialReferralCode?: string;
}

const COUNTRY_PREFIXES = [
    { code: '58', country: 'Venezuela', flag: '🇻🇪' },
    { code: '57', country: 'Colombia', flag: '🇨🇴' },
    { code: '1', country: 'USA/Canadá', flag: '🇺🇸' },
    { code: '34', country: 'España', flag: '🇪🇸' },
    { code: '56', country: 'Chile', flag: '🇨🇱' },
    { code: '593', country: 'Ecuador', flag: '🇪🇨' },
    { code: '51', country: 'Perú', flag: '🇵🇪' },
    { code: '54', country: 'Argentina', flag: '🇦🇷' },
];

const RegisterModal: React.FC<RegisterModalProps> = ({ isOpen, onClose, onRegister, registeredUsers = [], onOpenLogin, initialReferralCode }) => {
    const [name, setName] = useState<string>('');
    const [lastName, setLastName] = useState<string>('');
    const [phonePrefix, setPhonePrefix] = useState<string>('58');
    const [phone, setPhone] = useState<string>('');
    const [password, setPassword] = useState<string>('');
    const [referrerCode, setReferrerCode] = useState<string>(initialReferralCode || '');

    const [isLoading, setIsLoading] = useState(false);

    // Errors
    const [phoneError, setPhoneError] = useState<string>('');
    const [passwordError, setPasswordError] = useState<string>('');
    const [referrerError, setReferrerError] = useState<string>('');

    // Referral code validation
    const handleReferralCodeChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        const value = e.target.value.trim();
        setReferrerCode(value);

        if (value.length === 0) {
            setReferrerError('');
        } else {
            const codeExists = registeredUsers.some(u =>
                u.referralCode.toLowerCase() === value.toLowerCase()
            );
            const isVIPCode = ['VIP_RAY', 'RAYVIP'].includes(value.toUpperCase());
            const isFundadorCode = value.toUpperCase() === 'FUNDADOR';

            if (codeExists) {
                setReferrerError('✓ Código válido');
            } else if (isFundadorCode) {
                setReferrerError('✓ Código FUNDADOR Activo (3x Puntos)');
            } else if (isVIPCode) {
                setReferrerError('✓ Código Promo Activo (2x Puntos)');
            } else {
                setReferrerError('✗ Código no encontrado');
            }
        }
    }, [registeredUsers]);

    const handlePhoneChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        const value = e.target.value.replace(/\D/g, '');
        setPhone(value);

        if (value.length > 0 && value.length < 10) {
            setPhoneError('El número debe tener al menos 10 dígitos.');
        } else {
            setPhoneError('');
        }
    }, []);

    const handlePasswordChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        const value = e.target.value;
        setPassword(value);
        if (value.length > 0 && value.length < 4) {
            setPasswordError('Mínimo 4 caracteres.');
        } else {
            setPasswordError('');
        }
    }, []);

    const isFormValid = phone.length >= 10 && password.length >= 4 && !phoneError && !passwordError && (referrerError === '' || referrerError.startsWith('✓'));

    const handleSubmit = useCallback(async (e: React.FormEvent) => {
        e.preventDefault();

        if (!isFormValid || isLoading) return;

        setIsLoading(true);

        try {
            // 🛡️ SECURE REGISTRATION: Call Backend RPC
            const fullNormalizedPhone = phonePrefix + normalizePhone(phone);
            const autoGeneratedEmail = `${fullNormalizedPhone}@rayburger.app`;

            const { supabase } = await import('../../lib/supabase');

            if (!supabase) {
                setPhoneError('Error de conexión');
                return;
            }

            const { data, error } = await supabase.rpc('rpc_register_user', {
                p_phone: fullNormalizedPhone,
                p_name: name.trim() || 'Amante de Burger',
                p_password_hash: password, // In production, hash this client-side first
                p_email: autoGeneratedEmail,
                p_referral_code: referrerCode || null,
                p_fingerprint: getDeviceFingerprint()
            });

            if (error || !data?.success) {
                setPhoneError(data?.error || error?.message || 'Error al registrar');
                return;
            }

            // Success! Now fetch the created user to populate local state
            const { data: newUserData, error: fetchError } = await supabase
                .from('rb_users')
                .select('*')
                .eq('phone', fullNormalizedPhone)
                .single();

            if (fetchError || !newUserData) {
                console.error('Error fetching new user:', fetchError);
                return;
            }

            // Pass to parent (AuthContext) to update state
            // Map snake_case DB to camelCase App
            const mappedUser = mapDbUserToApp(newUserData);
            onRegister(mappedUser);

            // Clear form
            setName('');
            setPhone('');
            setPassword('');
            setReferrerCode('');
            setLastName('');
            setLastName('');

        } catch (error) {
            console.error("Register error", error);
            setPhoneError('Error de conexión. Intenta de nuevo.');
        } finally {
            setIsLoading(false);
        }

    }, [isFormValid, isLoading, name, phone, phonePrefix, password, referrerCode, onRegister]);

    useEffect(() => {
        if (!isOpen) {
            setName('');
            setLastName('');
            setPhone('');
            setPassword('');
            setReferrerCode(initialReferralCode || '');
            setPhoneError('');
            setPasswordError('');
            setReferrerError('');
        } else {
            if (initialReferralCode) {
                setReferrerCode(initialReferralCode);
                const codeExists = registeredUsers?.some(u => u.referralCode?.toLowerCase() === initialReferralCode.toLowerCase());
                if (codeExists) setReferrerError('✓ Código válido (desde enlace)');
            }
        }
    }, [isOpen, initialReferralCode, registeredUsers]);

    const handleLoginRedirect = useCallback(() => {
        onClose();
        onOpenLogin();
    }, [onClose, onOpenLogin]);


    return (
        <Modal isOpen={isOpen} onClose={onClose} title="Únete al Club RayBurger">
            <form onSubmit={handleSubmit} className="space-y-4">

                {/* Phone Field */}
                <div>
                    <label className="block text-white text-lg font-semibold mb-2">
                        WhatsApp Internacional <span className="text-red-500">*</span>
                    </label>
                    <div className="flex gap-2">
                        <select
                            value={phonePrefix}
                            onChange={(e) => setPhonePrefix(e.target.value)}
                            className="bg-gray-800 text-white border-2 border-gray-600 rounded-md px-2 py-3 focus:border-orange-500 transition-all text-sm outline-none"
                        >
                            {COUNTRY_PREFIXES.map(p => (
                                <option key={p.code} value={p.code}>{p.flag} +{p.code}</option>
                            ))}
                        </select>
                        <input
                            type="tel"
                            placeholder="Número (10 dígitos)"
                            value={phone}
                            onChange={handlePhoneChange}
                            required
                            className={`flex-1 px-4 py-3 rounded-md bg-gray-700 text-white border-2 ${phoneError ? 'border-red-500' : 'border-gray-600'} focus:border-orange-500 transition-all placeholder-gray-400 text-lg outline-none`}
                        />
                    </div>
                    {phoneError && (
                        <p className="text-red-500 text-sm mt-1 flex items-center">
                            {phoneError}
                        </p>
                    )}
                </div>

                {/* Password Field */}
                <div>
                    <label htmlFor="registerPassword" className="block text-white text-lg font-semibold mb-2">
                        Clave secreta <span className="text-red-500">*</span>
                    </label>
                    <input
                        id="registerPassword"
                        type="password"
                        placeholder="Algo que recuerdes"
                        value={password}
                        onChange={handlePasswordChange}
                        required
                        minLength={4}
                        className={`w-full px-4 py-3 rounded-md bg-gray-700 text-white border-2 ${passwordError ? 'border-red-500' : 'border-gray-600'} focus:border-orange-500 transition-all placeholder-gray-400 text-lg outline-none`}
                    />
                    {passwordError && <p className="text-red-500 text-sm mt-1">{passwordError}</p>}
                </div>

                {/* Info Fields */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    <div>
                        <label className="block text-white text-xs mb-1 uppercase font-bold tracking-wider">Nombre</label>
                        <input
                            type="text"
                            placeholder="Ej: Juan"
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                            className="w-full px-4 py-2 rounded-md bg-gray-700 text-white border border-gray-600 focus:border-orange-500 outline-none"
                        />
                    </div>
                    <div>
                        <label className="block text-white text-xs mb-1 uppercase font-bold tracking-wider">Apellido</label>
                        <input
                            type="text"
                            placeholder="Ej: Pérez"
                            value={lastName}
                            onChange={(e) => setLastName(e.target.value)}
                            className="w-full px-4 py-2 rounded-md bg-gray-700 text-white border border-gray-600 focus:border-orange-500 outline-none"
                        />
                    </div>
                </div>

                {/* Referrer */}
                <div className="mt-2">
                    <label className="block text-white text-sm mb-1 uppercase font-bold tracking-wider opacity-60">¿Tienes código de referido?</label>
                    <input
                        type="text"
                        placeholder="Pégalo aquí"
                        value={referrerCode}
                        onChange={handleReferralCodeChange}
                        className={`w-full px-4 py-2 rounded-md bg-gray-700 text-white border ${referrerError.startsWith('✓') ? 'border-green-500' : referrerError.startsWith('✗') ? 'border-red-500' : 'border-gray-600'} focus:border-orange-500 outline-none transition-colors`}
                    />
                    {referrerError && (
                        <p className={`text-sm mt-1 ${referrerError.startsWith('✓') ? 'text-green-400' : 'text-red-400'}`}>
                            {referrerError}
                        </p>
                    )}
                </div>

                <button
                    type="submit"
                    disabled={!isFormValid || isLoading}
                    className={`w-full mt-6 py-4 rounded-full text-lg font-black uppercase tracking-widest transition-all ${isFormValid && !isLoading ? 'bg-orange-600 hover:bg-orange-700 text-white shadow-xl active:scale-95' : 'bg-gray-600 text-gray-400 cursor-not-allowed'
                        }`}
                >
                    {isLoading ? <Loader2 className="w-6 h-6 animate-spin mx-auto" /> : '¡Registrarme! 🚀'}
                </button>
            </form>
            <p className="text-gray-400 text-center mt-6 text-sm">
                ¿Ya eres parte?{' '}
                <button type="button" onClick={handleLoginRedirect} className="text-orange-400 hover:underline font-bold">
                    Entra aquí
                </button>
            </p>
        </Modal>
    );
};

export default RegisterModal;
